/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Backend.Models.Course;
import Backend.Models.Lesson;
import Backend.Models.Student;
import Backend.Services.CourseService;
import Backend.Services.StudentService;



/**
 *
 * @author Mohamed Walaa
 */
public class StudentDashboard extends javax.swing.JPanel {
    
    StudentService studentService;
    
    /**
     * Creates new form StudentDashboard
     * @param student
     */
    public StudentDashboard(Student student) {
        studentService = new StudentService(student);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        availableCourseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enrolledCoursesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        enroll = new javax.swing.JButton();
        accesslessons = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        incompLessonButton = new javax.swing.JButton();
        compLessonButton = new javax.swing.JButton();

        setName(""); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setToolTipText("");

        availableCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor", "Number of Lessons"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(availableCourseTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enrolled Courses");

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(new javax.swing.border.MatteBorder(null));

        enrolledCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor", "Number of Lessons", "Progress"
            }
        ));
        jScrollPane2.setViewportView(enrolledCoursesTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Courses");

        enroll.setText("ENROLL");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        accesslessons.setText("ACCESS LESSONS");
        accesslessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesslessonsActionPerformed(evt);
            }
        });

        lessonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Name", "Completed?"
            }
        ));
        jScrollPane3.setViewportView(lessonTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Lessons");

        incompLessonButton.setText("Mark as incomplete");
        incompLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incompLessonButtonActionPerformed(evt);
            }
        });

        compLessonButton.setText("Mark as complete");
        compLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel3)
                                .addGap(38, 70, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(enroll)
                        .addGap(354, 354, 354)
                        .addComponent(accesslessons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(incompLessonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(compLessonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enroll)
                    .addComponent(accesslessons)
                    .addComponent(compLessonButton))
                .addGap(18, 18, 18)
                .addComponent(incompLessonButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTables() {
   DefaultTableModel enrolledModel = (DefaultTableModel) enrolledCoursesTable.getModel();
    DefaultTableModel lessonsModel = (DefaultTableModel) lessonTable.getModel();
    enrolledModel.setRowCount(0);
    for (Course c : studentService.getCourses()) {
        CourseService courseService = new CourseService(c);
        int total = c.getLessons().size();
    int completed = studentService.getLessons(c).size();

    enrolledModel.addRow(new Object[]{
        c.getCourseId(),
        c.getTitle(),
        courseService.getInstructorName(),
        completed + "/" + total   
    });
    }

    int selectedRow = enrolledCoursesTable.getSelectedRow();
    lessonsModel.setRowCount(0);

    if (selectedRow != -1) {
        int courseId = (int) enrolledModel.getValueAt(selectedRow, 0);
        Course selectedCourse = studentService.getCourseById(courseId);  
        if (selectedCourse != null) {
            for (Lesson l : selectedCourse.getLessons()) {
                boolean done = studentService.isLessonCompleted(l, selectedCourse);
                String doneText = "No";
                if(done){
                    doneText = "Yes";
                }
                else {
                    doneText = "No";
                }
                lessonsModel.addRow(new Object[]{ l.getLessonId(), l.getTitle(), doneText});
            }
        }
    }
}

    
    private void accesslessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesslessonsActionPerformed
                                            
    int selectedRow = enrolledCoursesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    int courseId = (Integer) enrolledCoursesTable.getValueAt(selectedRow, 0);

    Course selectedCourse = null;
    
    
    for (Course c : studentService.getCourses()) {
        if (c.getCourseId() == courseId) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Selected course not found.");
        return;
    }

    DefaultTableModel lessonsModel = (DefaultTableModel) lessonTable.getModel();
    lessonsModel.setRowCount(0);

    for (Lesson lesson : selectedCourse.getLessons()) {
        boolean completed = studentService.getLessons(selectedCourse).contains(lesson);
        lessonsModel.addRow(new Object[]{lesson.getLessonId(), lesson.getTitle(), completed ? "Yes" : "No"});
    }
    refreshTables();
    }//GEN-LAST:event_accesslessonsActionPerformed

    
    
    
    
    
    
    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
    int selectedRow = availableCourseTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course to enroll.");
        return;
    }

    int courseId = (Integer) availableCourseTable.getValueAt(selectedRow, 0);
    
    Course selectedCourse = null;
    for (Course c : studentService.getCourses()) {
        if (c.getCourseId() == courseId) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Selected course not found.");
        return;
    }
    
    boolean enrolled = studentService.enrollInCourse(selectedCourse);
    if (enrolled) {
        
        JOptionPane.showMessageDialog(this, "Enrolled in course: " + selectedCourse.getTitle());
        DefaultTableModel enrolledModel = (DefaultTableModel) enrolledCoursesTable.getModel();
        enrolledModel.setRowCount(0);
        for (Course c : studentService.getCourses()) {
            CourseService coursesService = new CourseService(c);
            int completedLessons = studentService.getLessons(c).size();
            enrolledModel.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                coursesService.getInstructorName(),
                c.getLessons().size(),
                completedLessons + "/" + c.getLessons().size()
            });
            
        }
        refreshTables();
    } else
        JOptionPane.showMessageDialog(this, "Already enrolled in this course.");
    
    }//GEN-LAST:event_enrollActionPerformed

    private void incompLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incompLessonButtonActionPerformed
                                               
    int selectedRow = lessonTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first.");
        return;
    }

    int lessonId = (Integer) lessonTable.getValueAt(selectedRow, 0);

    int selectedCourseRow = enrolledCoursesTable.getSelectedRow();
    if (selectedCourseRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    int courseId = (Integer) enrolledCoursesTable.getValueAt(selectedCourseRow, 0);

    Course selectedCourse = null;
    for (int id : studentService.getEnrolledCourses()) {
        Course c = studentService.getCourseById(id);
        if (c.getCourseId() == courseId) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse == null) return;
    CourseService coursesService = new CourseService(selectedCourse);
    Lesson lesson = coursesService.getLessonById(lessonId);
    studentService.getLessons(selectedCourse).remove(lesson);

    DefaultTableModel lessonsModel = (DefaultTableModel) lessonTable.getModel();
    lessonsModel.setValueAt("No", selectedRow, 2);

    DefaultTableModel enrolledModel = (DefaultTableModel) enrolledCoursesTable.getModel();
    int completedCount = studentService.getLessons(selectedCourse).size();
    int totalLessons = selectedCourse.getLessons().size();
    enrolledModel.setValueAt(completedCount + "/" + totalLessons, selectedCourseRow, 4);
    refreshTables();
    }//GEN-LAST:event_incompLessonButtonActionPerformed

    private void compLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compLessonButtonActionPerformed
    
    int selectedRow = lessonTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first.");
        return;
    }

    int lessonId = (Integer) lessonTable.getValueAt(selectedRow, 0);

    int selectedCourseRow = enrolledCoursesTable.getSelectedRow();
    if (selectedCourseRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    int courseId = (Integer) enrolledCoursesTable.getValueAt(selectedCourseRow, 0);

    Course selectedCourse = null;
    for (int id : studentService.getEnrolledCourses()) {
        Course c = studentService.getCourseById(id);
        if (c.getCourseId() == courseId) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse == null) return;
    CourseService coursesService = new CourseService(selectedCourse);
    Lesson lesson = coursesService.getLessonById(lessonId);
    studentService.markLessonAsCompleted(selectedCourse, lesson);

    DefaultTableModel lessonsModel = (DefaultTableModel) lessonTable.getModel();
    lessonsModel.setValueAt("Yes", selectedRow, 2);

    DefaultTableModel enrolledModel = (DefaultTableModel) enrolledCoursesTable.getModel();
    int completedCount = studentService.getLessons(selectedCourse).size();
    int totalLessons = selectedCourse.getLessons().size();
    enrolledModel.setValueAt(completedCount + "/" + totalLessons, selectedCourseRow, 4);
    refreshTables();
    }//GEN-LAST:event_compLessonButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesslessons;
    private javax.swing.JTable availableCourseTable;
    private javax.swing.JButton compLessonButton;
    private javax.swing.JButton enroll;
    private javax.swing.JTable enrolledCoursesTable;
    private javax.swing.JButton incompLessonButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lessonTable;
    // End of variables declaration//GEN-END:variables
}
